Added option to preserve spaces in filenames during export. Added additional error checks and cleaned up error checking methods in miqimport and miqexport scripts

diff --git a/bin/miqexport b/bin/miqexport
--- a/bin/miqexport
+++ b/bin/miqexport
@@ -1,70 +1,70 @@
 #!/usr/bin/env bash
 
-op_domain () {
-  DOMAIN_NAME=$1
-  EXPORT_DIR=$(readlink -v -f "$2")
-
-  if [ ! -d "$EXPORT_DIR" ]
+assert_num_args () {
+  num_args_received=$1
+  num_args_expected=$2
+  if [ "$num_args_received" -ne "$num_args_expected" ]
   then
-    echo "Export directory doesn't exist! [${EXPORT_DIR}]"
+    echo "Error: Wrong number of arguments (expected=$num_args_expected received=$num_args_received)"
+    usage
     exit 1
   fi
+}
 
+assert_export_dir_exists () {
+  export_dir=$1
+  if [ ! -d "$export_dir" ]
+  then
+    echo "Export directory doesn't exist! [${export_dir}]"
+    exit 1
+  fi
+}
+
+op_domain () {
+  assert_num_args $# 2
+  DOMAIN_NAME=$1
+  EXPORT_DIR=$(readlink -v -f "$2")
+  assert_export_dir_exists "$EXPORT_DIR"
+  
   pushd /var/www/miq/vmdb
-  bin/rake "rhconsulting:miq_ae_datastore:export[${DOMAIN_NAME}, ${EXPORT_DIR}]"
+  bin/rake "rhconsulting:miq_ae_datastore:export[${DOMAIN_NAME},${EXPORT_DIR}]"
   popd
 }
 
 op_reports () {
+  assert_num_args $# 1
   EXPORT_DIR=$(readlink -v -f "$1")
-
-  if [ ! -d "$EXPORT_DIR" ]
-  then
-    echo "Export directory doesn't exist! [${EXPORT_DIR}]"
-    exit 1
-  fi
-
+  assert_export_dir_exists "$EXPORT_DIR"
+  
   pushd /var/www/miq/vmdb
-  bin/rake "rhconsulting:miq_reports:export[${EXPORT_DIR}]"
+  bin/rake "rhconsulting:miq_reports:export[${EXPORT_DIR},keep_spaces=${KEEP_SPACES}]"
   popd
 }
 
 op_widgets () {
+  assert_num_args $# 1
   EXPORT_DIR=$(readlink -v -f "$1")
-
-  if [ ! -d "$EXPORT_DIR" ]
-  then
-    echo "Export directory doesn't exist! [${EXPORT_DIR}]"
-    exit 1
-  fi
-
+  assert_export_dir_exists "$EXPORT_DIR"
+  
   pushd /var/www/miq/vmdb
-  bin/rake "rhconsulting:miq_widgets:export[${EXPORT_DIR}]"
+  bin/rake "rhconsulting:miq_widgets:export[${EXPORT_DIR},keep_spaces=${KEEP_SPACES}]"
   popd
 }
 
 op_alerts () {
+  assert_num_args $# 1
   EXPORT_DIR=$(readlink -v -f "$1")
-
-  if [ ! -d "$EXPORT_DIR" ]
-  then
-    echo "Export directory doesn't exist! [${EXPORT_DIR}]"
-    exit 1
-  fi
-
+  assert_export_dir_exists "$EXPORT_DIR"
+  
   pushd /var/www/miq/vmdb
-  bin/rake "rhconsulting:miq_alerts:export[${EXPORT_DIR}]"
+  bin/rake "rhconsulting:miq_alerts:export[${EXPORT_DIR},keep_spaces=${KEEP_SPACES}]"
   popd
 }
 
 op_alertsets () {
+  assert_num_args $# 1
   EXPORT_DIR=$(readlink -v -f "$1")
-
-  if [ ! -d "$EXPORT_DIR" ]
-  then
-    echo "Export directory doesn't exist! [${EXPORT_DIR}]"
-    exit 1
-  fi
+  assert_export_dir_exists "$EXPORT_DIR"
 
   pushd /var/www/miq/vmdb
   bin/rake "rhconsulting:miq_alertsets:export[${EXPORT_DIR}]"
@@ -72,118 +72,86 @@ op_alertsets () {
 }
 
 op_policies () {
+  assert_num_args $# 1
   EXPORT_DIR=$(readlink -v -f "$1")
-
-  if [ ! -d "$EXPORT_DIR" ]
-  then
-    echo "Export directory doesn't exist! [${EXPORT_DIR}]"
-    exit 1
-  fi
+  assert_export_dir_exists "$EXPORT_DIR"
 
   pushd /var/www/miq/vmdb
-  bin/rake "rhconsulting:miq_policies:export[${EXPORT_DIR}]"
+  bin/rake "rhconsulting:miq_policies:export[${EXPORT_DIR},keep_spaces=${KEEP_SPACES}]"
   popd
 }
 
 op_provision_dialogs () {
+  assert_num_args $# 1
   EXPORT_DIR=$(readlink -v -f "$1")
-
-  if [ ! -d "$EXPORT_DIR" ]
-  then
-    echo "Export directory doesn't exist! [${EXPORT_DIR}]"
-    exit 1
-  fi
+  assert_export_dir_exists "$EXPORT_DIR"
 
   pushd /var/www/miq/vmdb
-  bin/rake --trace "rhconsulting:provision_dialogs:export[${EXPORT_DIR}]"
+  bin/rake --trace "rhconsulting:provision_dialogs:export[${EXPORT_DIR},keep_spaces=${KEEP_SPACES}]"
   popd
 }
 
 op_service_dialogs () {
+  assert_num_args $# 1
   EXPORT_DIR=$(readlink -v -f "$1")
-
-  if [ ! -d "$EXPORT_DIR" ]
-  then
-    echo "Export directory doesn't exist! [${EXPORT_DIR}]"
-    exit 1
-  fi
+  assert_export_dir_exists "$EXPORT_DIR"
 
   pushd /var/www/miq/vmdb
-  bin/rake "rhconsulting:service_dialogs:export[${EXPORT_DIR}]"
+  bin/rake "rhconsulting:service_dialogs:export[${EXPORT_DIR},keep_spaces=${KEEP_SPACES}]"
   popd
 }
 
 op_service_catalogs () {
+  assert_num_args $# 1
   EXPORT_DIR=$(readlink -v -f "$1")
-
-  if [ ! -d "$EXPORT_DIR" ]
-  then
-    echo "Export directory doesn't exist! [${EXPORT_DIR}]"
-    exit 1
-  fi
+  assert_export_dir_exists "$EXPORT_DIR"
 
   pushd /var/www/miq/vmdb
-  bin/rake "rhconsulting:service_catalogs:export[${EXPORT_DIR}]"
+  bin/rake "rhconsulting:service_catalogs:export[${EXPORT_DIR},keep_spaces=${KEEP_SPACES}]"
   popd
 }
 
 op_roles () {
+  assert_num_args $# 1
   EXPORT_FILE=$(readlink -v -f "$1")
   EXPORT_DIR=$(dirname "$EXPORT_FILE")
-
-  if [ ! -d "$EXPORT_DIR" ]
-  then
-    echo "Export directory doesn't exist! [${EXPORT_DIR}]"
-    exit 1
-  fi
+  assert_export_dir_exists "$EXPORT_DIR"
 
   pushd /var/www/miq/vmdb
-  bin/rake "rhconsulting:roles:export[${EXPORT_FILE}]"
+  bin/rake "rhconsulting:roles:export[${EXPORT_FILE},keep_spaces=${KEEP_SPACES}]"
   popd
 }
 
 op_tags () {
+  assert_num_args $# 1
   EXPORT_FILE=$(readlink -v -f "$1")
   EXPORT_DIR=$(dirname "$EXPORT_FILE")
-
-  if [ ! -d "$EXPORT_DIR" ]
-  then
-    echo "Export directory doesn't exist! [${EXPORT_DIR}]"
-    exit 1
-  fi
+  assert_export_dir_exists "$EXPORT_DIR"
 
   pushd /var/www/miq/vmdb
-  bin/rake "rhconsulting:tags:export[${EXPORT_FILE}]"
+  bin/rake "rhconsulting:tags:export[${EXPORT_FILE},keep_spaces=${KEEP_SPACES}]"
   popd
 }
 
 op_buttons () {
+  assert_num_args $# 1
   EXPORT_FILE=$(readlink -v -f "$1")
   EXPORT_DIR=$(dirname "$EXPORT_FILE")
-
-  if [ ! -d "$EXPORT_DIR" ]
-  then
-    echo "Export directory doesn't exist! [${EXPORT_DIR}]"
-    exit 1
-  fi
+  assert_export_dir_exists "$EXPORT_DIR"
 
   pushd /var/www/miq/vmdb
-  bin/rake "rhconsulting:buttons:export[${EXPORT_FILE}]"
+  bin/rake "rhconsulting:buttons:export[${EXPORT_FILE},keep_spaces=${KEEP_SPACES}]"
   popd
 }
 
 op_customization_templates () {
+  assert_num_args $# 1
   EXPORT_FILE=$(readlink -v -f "$1")
   EXPORT_DIR=$(dirname "$EXPORT_FILE")
-
-  if [ ! -d "$EXPORT_DIR" ]
-  then
-    echo "Export directory doesn't exist! [${EXPORT_DIR}]"
-    exit 1
-  fi
+  assert_export_dir_exists "$EXPORT_DIR"
 
   pushd /var/www/miq/vmdb
-  bin/rake "rhconsulting:customization_templates:export[${EXPORT_FILE}]"
+  bin/rake "rhconsulting:customization_templates:export[${EXPORT_FILE},keep_spaces=${KEEP_SPACES}]"
   popd
 }
 
@@ -201,10 +169,43 @@ contains () {
   return 1  
 }
 
+parse_arguments () {
+  # initialize non-required arguments before the loop in case they are
+  # not present in the command line
+  KEEP_SPACES="false"
+
+  # http://stackoverflow.com/questions/402377/using-getopts-in-bash-shell-script-to-get-long-and-short-command-line-options
+  # http://stackoverflow.com/questions/14786984/best-way-to-parse-cmdline-args-bash
+  while [[ $# -ge 1 ]]
+  do
+    arg="$1"
+    case "$arg" in
+      -s|--keep-spaces)
+        KEEP_SPACES="true"
+        shift # past the argument
+        ;;
+      --)
+        shift # past the argument
+        break # stop parsing arguments
+        ;;
+      *)
+        # unknown option
+        break # stop parsing arguments
+        ;;
+    esac
+  done
+
+  # if there are any required arguments check for them here
+
+  # pass the shifted arguments back to the caller
+  remaining_args="$@"
+}
+
 parse_action () {
   AVAILABLE_PARSERS=`compgen -A function | grep '^op_'`
 
-  op_func="op_$1"
+  obj_type="$1"
+  op_func="op_${obj_type}"
   contains $op_func $AVAILABLE_PARSERS; VALID_OP=$?
 
   if [ $VALID_OP -eq 0 ]
@@ -212,7 +213,9 @@ parse_action () {
     shift
     $op_func "$@"
   else
+    echo "Error: Unknown object type: $obj_type"
     usage
+    exit 1
   fi
 }
 
@@ -220,7 +223,7 @@ usage () {
 progname=`basename $0`
 
   cat << EOF
-Usage: $progname <object_type> <additional_params> <exportdest>
+Usage: $progname [OPTION...] <object_type> <additional_params> <exportdest>
 
 This command exports the specified object type into the <exportdest>,
 which may be a file or directory.
@@ -245,6 +248,11 @@ Available Object Types:
                                    Automate Engine Datastore. <name> MUST
                                    be specified.
 
+Options:
+  -s, --keep-spaces                Export filenames with spaces instead of
+                                   replacing the spaces with underscores.
+                                   (this preserves old behavior)
+
 Report bugs and feature requests to
 https://github.com/rhtconsulting/cfme-rhconsulting-scripts
 
@@ -252,5 +260,6 @@ EOF
 
 }
 
-parse_action "$@"
-
+parse_arguments "$@"
+parse_action "$remaining_args"
+exit 0
diff --git a/bin/miqimport b/bin/miqimport
--- a/bin/miqimport
+++ b/bin/miqimport
@@ -1,28 +1,49 @@
 #!/usr/bin/env bash
 
-op_domain () {
-  DOMAIN_NAME=$1
-  IMPORT_DIR=$(readlink -v -f "$2")
-
-  if [ ! -d "$IMPORT_DIR" ]
+assert_num_args () {
+  num_args_received=$1
+  num_args_expected=$2
+  if [ "$num_args_received" -ne "$num_args_expected" ]
   then
-    echo "Import directory doesn't exist! [${IMPORT_DIR}]"
+    echo "Error: Wrong number of arguments (expected=$num_args_expected received=$num_args_received)"
+    usage
     exit 1
   fi
+}
+
+assert_import_dir_exists () {
+  import_dir=$1
+  if [ ! -d "$import_dir" ]
+  then
+    echo "Import directory doesn't exist! [${import_dir}]"
+    exit 1
+  fi
+}
+
+assert_import_file_or_dir_exists () {
+  import_file_or_dir=$1
+  if [ ! -f "$import_file_or_dir" ] && [ ! -d "$import_file_or_dir" ]
+  then
+    echo "Import file/directory doesn't exist! [${import_file_or_dir}]"
+    exit 1
+  fi
+}
+
+op_domain () {
+  assert_num_args $# 2
+  DOMAIN_NAME=$1
+  IMPORT_DIR=$(readlink -v -f "$2")
+  assert_import_dir_exists "$IMPORT_DIR"
 
   pushd /var/www/miq/vmdb
-  bin/rake "rhconsulting:miq_ae_datastore:import[${DOMAIN_NAME}, ${IMPORT_DIR}]"
+  bin/rake "rhconsulting:miq_ae_datastore:import[${DOMAIN_NAME},${IMPORT_DIR}]"
   popd
 }
 
 op_reports () {
+  assert_num_args $# 1
   IMPORT_DIR=$(readlink -v -f "$1")
-
-  if [ ! -d "$IMPORT_DIR" ]
-  then
-    echo "Import directory doesn't exist! [${IMPORT_DIR}]"
-    exit 1
-  fi
+  assert_import_dir_exists "$IMPORT_DIR"
 
   pushd /var/www/miq/vmdb
   bin/rake "rhconsulting:miq_reports:import[${IMPORT_DIR}]"
@@ -30,13 +51,9 @@ op_reports () {
 }
 
 op_widgets () {
+  assert_num_args $# 1
   IMPORT_DIR=$(readlink -v -f "$1")
-
-  if [ ! -d "$IMPORT_DIR" ]
-  then
-    echo "Import directory doesn't exist! [${IMPORT_DIR}]"
-    exit 1
-  fi
+  assert_import_dir_exists "$IMPORT_DIR"
 
   pushd /var/www/miq/vmdb
   bin/rake "rhconsulting:miq_widgets:import[${IMPORT_DIR}]"
@@ -44,27 +61,19 @@ op_widgets () {
 }
 
 op_alerts () {
+  assert_num_args $# 1  
   IMPORT_FILE_OR_DIR=$(readlink -v -f "$1")
-
-  if [ ! -f "$IMPORT_FILE_OR_DIR" ] && [ ! -d "$IMPORT_FILE_OR_DIR" ]
-  then
-    echo "Import file/directory doesn't exist! [${IMPORT_FILE_OR_DIR}]"
-    exit 1
-  fi
-
+  assert_import_file_or_dir_exists "$IMPORT_FILE_OR_DIR"
+  
   pushd /var/www/miq/vmdb
   bin/rake "rhconsulting:miq_alerts:import[${IMPORT_FILE_OR_DIR}]"
   popd
 }
 
 op_alertsets () {
+  assert_num_args $# 1
   IMPORT_FILE_OR_DIR=$(readlink -v -f "$1")
-
-  if [ ! -f "$IMPORT_FILE_OR_DIR" ] && [ ! -d "$IMPORT_FILE_OR_DIR" ]
-  then
-    echo "Import file/directory doesn't exist! [${IMPORT_FILE_OR_DIR}]"
-    exit 1
-  fi
+  assert_import_file_or_dir_exists "$IMPORT_FILE_OR_DIR"
 
   pushd /var/www/miq/vmdb
   bin/rake "rhconsulting:miq_alertsets:import[${IMPORT_FILE_OR_DIR}]"
@@ -72,13 +81,9 @@ op_alertsets () {
 }
 
 op_policies () {
+  assert_num_args $# 1
   IMPORT_DIR=$(readlink -v -f "$1")
-
-  if [ ! -d "$IMPORT_DIR" ]
-  then
-    echo "Import directory doesn't exist! [${IMPORT_DIR}]"
-    exit 1
-  fi
+  assert_import_dir_exists "$IMPORT_DIR"
 
   pushd /var/www/miq/vmdb
   bin/rake "rhconsulting:miq_policies:import[${IMPORT_DIR}]"
@@ -86,13 +91,9 @@ op_policies () {
 }
 
 op_provision_dialogs () {
+  assert_num_args $# 1
   IMPORT_FILE_OR_DIR=$(readlink -v -f "$1")
-
-  if [ ! -f "$IMPORT_FILE_OR_DIR" ] && [ ! -d "$IMPORT_FILE_OR_DIR" ]
-  then
-    echo "Import file/directory doesn't exist! [${IMPORT_FILE_OR_DIR}]"
-    exit 1
-  fi
+  assert_import_file_or_dir_exists "$IMPORT_FILE_OR_DIR"
 
   pushd /var/www/miq/vmdb
   bin/rake "rhconsulting:provision_dialogs:import[${IMPORT_FILE_OR_DIR}]"
@@ -100,13 +101,9 @@ op_provision_dialogs () {
 }
 
 op_service_dialogs () {
+  assert_num_args $# 1
   IMPORT_FILE_OR_DIR=$(readlink -v -f "$1")
-
-  if [ ! -f "$IMPORT_FILE_OR_DIR" ] && [ ! -d "$IMPORT_FILE_OR_DIR" ]
-  then
-    echo "Import file/directory doesn't exist! [${IMPORT_FILE_OR_DIR}]"
-    exit 1
-  fi
+  assert_import_file_or_dir_exists "$IMPORT_FILE_OR_DIR"
 
   pushd /var/www/miq/vmdb
   bin/rake "rhconsulting:service_dialogs:import[${IMPORT_FILE_OR_DIR}]"
@@ -114,13 +111,9 @@ op_service_dialogs () {
 }
 
 op_service_catalogs () {
+  assert_num_args $# 1
   IMPORT_DIR=$(readlink -v -f "$1")
-
-  if [ ! -d "$IMPORT_DIR" ]
-  then
-    echo "Import directory doesn't exist! [${IMPORT_DIR}]"
-    exit 1
-  fi
+  assert_import_dir_exists "$IMPORT_DIR"
 
   pushd /var/www/miq/vmdb
   bin/rake "rhconsulting:service_catalogs:import[${IMPORT_DIR}]"
@@ -128,13 +121,9 @@ op_service_catalogs () {
 }
 
 op_roles () {
+  assert_num_args $# 1
   IMPORT_FILE_OR_DIR=$(readlink -v -f "$1")
-
-  if [ ! -f "$IMPORT_FILE_OR_DIR" ] && [ ! -d "$IMPORT_FILE_OR_DIR" ]
-  then
-    echo "Import file/directory doesn't exist! [${IMPORT_FILE_OR_DIR}]"
-    exit 1
-  fi
+  assert_import_file_or_dir_exists "$IMPORT_FILE_OR_DIR"
 
   pushd /var/www/miq/vmdb
   bin/rake "rhconsulting:roles:import[${IMPORT_FILE_OR_DIR}]"
@@ -142,13 +131,9 @@ op_roles () {
 }
 
 op_tags () {
+  assert_num_args $# 1
   IMPORT_FILE_OR_DIR=$(readlink -v -f "$1")
-
-  if [ ! -f "$IMPORT_FILE_OR_DIR" ] && [ ! -d "$IMPORT_FILE_OR_DIR" ]
-  then
-    echo "Import file/directory doesn't exist! [${IMPORT_FILE_OR_DIR}]"
-    exit 1
-  fi
+  assert_import_file_or_dir_exists "$IMPORT_FILE_OR_DIR"
 
   pushd /var/www/miq/vmdb
   bin/rake "rhconsulting:tags:import[${IMPORT_FILE_OR_DIR}]"
@@ -156,13 +141,9 @@ op_tags () {
 }
 
 op_buttons () {
+  assert_num_args $# 1
   IMPORT_FILE_OR_DIR=$(readlink -v -f "$1")
-
-  if [ ! -f "$IMPORT_FILE_OR_DIR" ] && [ ! -d "$IMPORT_FILE_OR_DIR" ]
-  then
-    echo "Import file/directory doesn't exist! [${IMPORT_FILE_OR_DIR}]"
-    exit 1
-  fi
+  assert_import_file_or_dir_exists "$IMPORT_FILE_OR_DIR"
 
   pushd /var/www/miq/vmdb
   bin/rake "rhconsulting:buttons:import[${IMPORT_FILE_OR_DIR}]"
@@ -170,13 +151,9 @@ op_buttons () {
 }
 
 op_customization_templates () {
+  assert_num_args $# 1
   IMPORT_FILE_OR_DIR=$(readlink -v -f "$1")
-
-  if [ ! -f "$IMPORT_FILE_OR_DIR" ] && [ ! -d "$IMPORT_FILE_OR_DIR" ]
-  then
-    echo "Import file/directory doesn't exist! [${IMPORT_FILE_OR_DIR}]"
-    exit 1
-  fi
+  assert_import_file_or_dir_exists "$IMPORT_FILE_OR_DIR"
 
   pushd /var/www/miq/vmdb
   bin/rake "rhconsulting:customization_templates:import[${IMPORT_FILE_OR_DIR}]"
@@ -200,7 +177,8 @@ contains () {
 parse_action () {
   AVAILABLE_PARSERS=`compgen -A function | grep '^op_'`
 
-  op_func="op_$1"
+  obj_type="$1"
+  op_func="op_${obj_type}"
   contains $op_func $AVAILABLE_PARSERS; VALID_OP=$?
 
   if [ $VALID_OP -eq 0 ]
@@ -208,7 +186,9 @@ parse_action () {
     shift
     $op_func "$@"
   else
+    echo "Error: Unknown object type: $obj_type"
     usage
+    exit 1
   fi
 }
 
@@ -247,4 +227,4 @@ EOF
 }
 
 parse_action "$@"
-
+exit 0
